title: poster Board Hire 
description: >
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxA beautiful, fast, AMP-compliant Jekyll theme based on Tufte CSS.
baseurl: "/immaculate"
url: "https://github.com/espirus/test-immaculate"
paginate:	2 # The number of posts to show per page on your homepage
name: "Lau Siaw Young"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
